In [1]:
import numpy as np

In [2]:
wc = np.array([0.81, 0.73])
wi = np.array([0.62, 0.34])
wf = np.array([0.23, 0.83])
wo = np.array([0.25, 0.34])

In [3]:
uc = 0.78
ui = 0.68
uf = 0.14
uo = 0.12

In [5]:
x0 = np.array([0.59, 0.54])
label0 = 0.22

In [6]:
x1 = np.array([0.91, 0.27])
label1 = 0.33

In [42]:
c_prev = np.zeros_like(x0)
c_prev

array([0., 0.])

In [43]:
h_prev = np.zeros_like(x0)
h_prev

array([0., 0.])

In [15]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [34]:
def lstm_forward(x, h_prev, c_prev, wc, wi, wf, wo, uc, ui, uf, uo):
    f = sigmoid(np.dot(wf, x) + uf * h_prev)
    i = sigmoid(np.dot(wi, x) + ui * h_prev)
    o = sigmoid(np.dot(wo, x) + uo * h_prev)
    c_bar = np.tanh(np.dot(wc, x) + uc * h_prev)

    c = f * h_prev + i * c_bar
    h = o * np.tanh(c)

    return h, c

In [41]:
for i in range(10):
    h0, c0 = lstm_forward(x0, h_prev, c_prev, wc, wi, wf, wo, uc, ui, uf, uo)
    h_prev, c_prev = h0, c0
    print(h0, c0)

[0.24332474 0.24332474] [0.44534411 0.44534411]
[0.35081486 0.35081486] [0.68614059 0.68614059]
[0.39002636 0.39002636] [0.79028568 0.79028568]
[0.40311277 0.40311277] [0.82793323 0.82793323]
[0.4073402 0.4073402] [0.84045718 0.84045718]
[0.40869107 0.40869107] [0.84449861 0.84449861]
[0.40912122 0.40912122] [0.8457896 0.8457896]
[0.40925804 0.40925804] [0.84620064 0.84620064]
[0.40930155 0.40930155] [0.84633138 0.84633138]
[0.40931538 0.40931538] [0.84637295 0.84637295]


In [36]:
h1, c1 = lstm_forward(x1, h0, c0, wc, wi, wf, wo, uc, ui, uf, uo)
h1, c1

(array([0.35854321, 0.35854321]), array([0.71144774, 0.71144774]))