In [45]:
import numpy as np

In [46]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
print("Input Given: \n", X)

y = np.array([[0], [1], [1], [0]])
print("Expected Output: \n", y)

Input Given: 
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Expected Output: 
 [[0]
 [1]
 [1]
 [0]]


In [47]:
w11 = np.asarray([1, 1])
w12 = np.asarray([1, 1])
w2 = np.asarray([-1, 1])

B1 = np.asarray([-0.5, -0.5])
B2 = np.asarray([-0.5])

In [48]:
w11, w12, w2, B1, B2

(array([1, 1]),
 array([1, 1]),
 array([-1,  1]),
 array([-0.5, -0.5]),
 array([-0.5]))

In [49]:
x = X[0]
print(x)

[0 0]


In [50]:
len(w11)

2

In [51]:
def summation(z, w11, w12, B1):
    sumh = [0, 0]
    for i in range(len(x)):
        sumh[i] = (x[0]*w11[i]+x[1]*w12[i]+B1[i])
    return sumh

In [52]:
sumv = summation(x, w11, w12, B1)
print(sumv)

[-0.5, -0.5]


In [53]:
def Heaviside(net):
    if net >= 0:
        return 1
    else:
        return 0

In [54]:
hidden = [0, 0]
for i in range(len(sumv)):
    hidden[i] = Heaviside(sumv[i])
print(hidden)

[0, 0]


In [55]:
sumo = np.dot(hidden, w2) + B2[0]
y_pred = Heaviside(sumo)
print(y_pred)

0


In [56]:
y_pred = []
for i in range(X.shape[0]):
    x = X[i]
    sumv = summation(x, w11, w12, B1)
    hidden =  [0, 0]
    for i in range(len(sumv)):
        hidden[i] =Heaviside(sumv[i])   
    sumo = np.dot(hidden, w2) + B2[0]
    y_pred.append(Heaviside(sumo)) 



In [57]:
print("Computed Output: ",y_pred)

Computed Output:  [0, 0, 0, 0]
